;**********
; Constants
;**********

; PPU
PPUCTRL := $2000
PPUMASK := $2001
PPUSTATUS := $2002
PPUSCROLL := $2005
PPUADDR := $2006
PPUDATA := $2007

; APU
APU := $4000
APU_SQ1_VOL   := $4000
APU_SQ1_SWEEP := $4001
APU_SQ1_LO    := $4002
APU_SQ1_HI    := $4003
APU_SQ2_VOL   := $4004
APU_SQ2_SWEEP := $4005
APU_SQ2_LO    := $4006
APU_SQ2_HI    := $4007
APU_TRI_LINEAR := $4008
APU_TRI_LO     := $400A
APU_TRI_HI     := $400B
APU_NOISE_VOL := $400C
APU_NOISE_LO  := $400E
APU_NOISE_HI  := $400F
APU_DMC_FREQ  := $4010
APU_DMC_RAW   := $4011
APU_DMC_START := $4012
APU_DMC_LEN   := $4013
APU_SND_CHN := $4015
APU_CTRL    := $4015
APU_STATUS  := $4015
APU_FRAME   := $4017

; OAM
OAMDMA := $4014

; IO
JOYPAD1 := $4016
JOYPAD2 := $4017

; Game
LASER_MAX = 48
POS_OUTOFMAP = $F0
LEVEL_MAX = 23
MAXLASERPERFRAME = 3 ; need to be a power of 2-1
TILE_TABLE_SIZE = $15
BTN_TIMER = 16

; Game Stage
.enum STG
    LEVEL_EDIT
    MENU_LOAD
    MENU
    LEVEL_LOAD
    LEVEL_PLAY
    LEVEL_WIN
    LEVEL_LOOSE
.endenum

; Meta Tiles
.enum MTILE
    VOID
    WALL
    GROUND
    UIBOT
    GLASS
    LASER_HOR
    LASER_VER
    LASER_CROSS
    SKULL
    SKULL_H
    SKULL_V
    SKULL_ON
    NULL_0C
    NULL_0D
    NULL_0E
    NULL_0F

    EMIT_UP
    EMIT_DOWN
    EMIT_LEFT
    EMIT_RIGHT
    EMIT_UP_ON
    EMIT_DOWN_ON
    EMIT_LEFT_ON
    EMIT_RIGHT_ON
    RECEIVE_UP
    RECEIVE_DOWN
    RECEIVE_LEFT
    RECEIVE_RIGHT
    RECEIVE_UP_ON
    RECEIVE_DOWN_ON
    RECEIVE_LEFT_ON
    RECEIVE_RIGHT_ON

    MIRROR_1
    MIRROR_2
    MIRROR_CROSS1
    MIRROR_CROSS2
    MIRROR_UL
    MIRROR_UR
    MIRROR_DL
    MIRROR_DR
    MIRRORC_UL
    MIRRORC_UR
    MIRRORC_DL
    MIRRORC_DR
    NULL_2C
    NULL_2D
    NULL_2E
    NULL_2F

    DOOR_H
    DOOR_V
    DOOR_H_ON
    DOOR_V_ON
    SPLITTER_H
    SPLITTER_V
    SPLITTER_H_ON
    SPLITTER_V_ON
    MERGER_H
    MERGER_V
    MERGER_H_T
    MERGER_V_L
    MERGER_H_B
    MERGER_V_R
    MERGER_H_ON
    MERGER_V_ON

    TITLE_NAME_1
    TITLE_NAME_2
    TITLE_NAME_3
    TITLE_NAME_4
    TITLE_NAME_5
    TITLE_EFFECT_1
    TITLE_EFFECT_2
    TITLE_EFFECT_3
    TITLE_EFFECT_4
    TITLE_EFFECT_5
    TITLE_LASER
    TITLE_LASER_DIAGONAL_1
    TITLE_LASER_DIAGONAL_2
    TITLE_SAPHYR
    TITLE_SAFYRUS_GAMES_1
    TITLE_SAFYRUS_GAMES_2

    SPE_ARRAY = $FF
.endenum


.enum SPR
    NULL
    CURS1
    CURS2
    ZERO
    SELECTED
    BTN_A
    BTN_B
    BTN_START
    BTN_SELECT
    BTN_UP
    BTN_DOWN
    BTN_LEFT
    BTN_RIGHT
.endenum